<a href="https://colab.research.google.com/github/jdaavi/Programa-o-CD-UFC-/blob/main/Aula_07_programa%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Função numpy
import numpy as np
np_2d = np.array([[1.73,1.68,1.71,1.89,1.79],
              [65.4,59.2,63.6,88.4,68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [ ]:
#Função shape, para descobrir o número de linhas e colunas
np_2d.shape

(2, 5)

In [ ]:
 np.array([[1.73,1.68,1.71,1.89,1.79],
              [65.4,59.2,63.6,88.4,"68.7"]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [ ]:
#Novo array de 3 linhas e 5 colunas
np_3d = np.array([[1.73,1.68,1.71,1.89,1.79],
                  [1,2,3,4,5],[2.0,2.1,2.3,2.4,2.5]])
np_3d.shape

#Localizando o termo 3 da segunda linha
print(np_3d[0,2])
#localizando todos os termos da terceira linha
print(np_3d[2, :])
#localizando o segundo e terceiro termo de todas as linhas
print(np_3d[: , 1:3 ])

1.71
[2.  2.1 2.3 2.4 2.5]
[[1.68 1.71]
 [2.   3.  ]
 [2.1  2.3 ]]


In [ ]:
#Novo array de 3 linhas e 3 colunas
np_4d = np.array([[3,4,5],[6,7,8],[9,10,11]])
np_4d.shape

(3, 3)

In [ ]:
#Lista baseball - Questões
Baseball = [180,215,210,210,188,176,209,208]
import numpy as np

#convertendo a lista Baseball
np_baseball = np.array(Baseball)
print(np_baseball)

#Dimensões da nova lista baseball
np_baseball.shape

[180 215 210 210 188 176 209 208]


(8,)

In [ ]:
#Questões 
import random as rd
import numpy as np

#Geração de números entre 150 e 209
height = range(150,210)
#Geração de números entre 50 e 149
weight = range(50,149)
#amostra randomica de height
height = rd.sample(height,20)
print(height)
#amostra randomica de weight
weight = rd.sample(weight,20)
print(weight)
#convertendo height para array e normalizar o multiplicador por 0.01
height_array = np.array(height)*0.01
print(height_array)
print(height_array)
#convertendo weight em array
weight_array = np.array(weight)
print(weight_array)
#
bmi = weight_array/height_array**2

[195, 185, 192, 196, 206, 194, 208, 193, 158, 202, 191, 154, 207, 167, 176, 164, 198, 189, 188, 174]
[134, 128, 98, 106, 139, 62, 69, 140, 55, 51, 74, 108, 75, 132, 112, 103, 70, 82, 113, 127]
[1.95 1.85 1.92 1.96 2.06 1.94 2.08 1.93 1.58 2.02 1.91 1.54 2.07 1.67
 1.76 1.64 1.98 1.89 1.88 1.74]
[1.95 1.85 1.92 1.96 2.06 1.94 2.08 1.93 1.58 2.02 1.91 1.54 2.07 1.67
 1.76 1.64 1.98 1.89 1.88 1.74]
[134 128  98 106 139  62  69 140  55  51  74 108  75 132 112 103  70  82
 113 127]


In [ ]:
#Fórmula do BMI
bmi = weight_array/height_array**2
print(bmi)
#Verificação onde BMI é menor que 21 e exibição
light = bmi < 21
print(light)

[35.2399737  37.39956172 26.58420139 27.59266972 32.75520784 16.47358912
 15.94859467 37.58490161 22.03172568 12.49877463 20.28453167 45.53887671
 17.50332563 47.33048872 36.15702479 38.29565735 17.85532089 22.95568433
 31.97148031 41.9474171 ]
[False False False False False  True  True False False  True  True False
  True False False False  True False False False]
[ 55  51  74 108  75 132 112]


In [66]:
#Questões
baseball = [[180,78.4],
            [215,182.7],
            [210,98.5],
            [188,75.2]]
# importando numpy
import numpy as np
           
#criando np_baseball
np_baseball = np.array(baseball)
np_baseball

#Print da terceira linha de np_baseball
print(np_baseball[2, :])

#Nova variável que recebe a segunda linha
np_weight_lb = np_baseball[:, 1]
print(np_weight_lb)

#Print da primeira coluna, da segunda lista de np_baseball
print(np_baseball[1,0])

#Tirando a mediana
np.median(np_baseball[: ,0])

[210.   98.5]
[ 78.4 182.7  98.5  75.2]
215.0


199.0